///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Business.TableStorage
{
	using Common.BusinessObjects;
	using Microsoft.WindowsAzure.Storage.Table;
	using System;

	/// <summary>
	/// Represents an experience level
	/// </summary>
	public class ExperienceLevelTableStorage : TableEntity, ITableStorageEntity
	{
		/// <summary>
		/// Creates a new instance of the ExperienceLevelTableStorage class.
		/// </summary>
		public ExperienceLevelTableStorage() { }

		/// <summary>
		/// The level of this experience level
		/// </summary>
		public int Level { get; set; }

		/// <summary>
		/// The experience required to achieve the level
		/// </summary>
		public int ExperienceRequired { get; set; }

	}
}