///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Common.BusinessObjects
{
	using System;
	using System.Collections.Generic;

	/// <summary>
	/// Represents an experience level
	/// </summary>
	public class ExperienceLevel : IBusinessObjectEntity
	{
		/// <summary>
		/// Creates a new instance of the ExperienceLevel class.
		/// </summary>
		public ExperienceLevel() { }

		/// <summary>
		/// The level of this experience level
		/// </summary>
		public int Level { get; set; }

		/// <summary>
		/// The experience required to achieve the level
		/// </summary>
		public int ExperienceRequired { get; set; }

	}
}