///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Business.Cache
{
	using Common.BusinessObjects;
	using Business.ProtoSerializable;
	using ProtoBuf;
	using System;
	using System.Collections.Generic;

	/// <summary>
	/// Represents an experience level
	/// </summary>
	[ProtoContract]
	[Serializable]
	public class ExperienceLevelCacheable : ICacheEntity
	{
		/// <summary>
		/// Creates a new instance of the ExperienceLevelCacheable class.
		/// </summary>
		public ExperienceLevelCacheable() { }

		/// <summary>
		/// The level of this experience level
		/// </summary>
		[ProtoMember(1)]
		public int Level { get; set; }

		/// <summary>
		/// The experience required to achieve the level
		/// </summary>
		[ProtoMember(2)]
		public int ExperienceRequired { get; set; }

	}
}