///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Business.Cache
{
	using Common.BusinessObjects;
	using Business.ProtoSerializable;
	using ProtoBuf;
	using System;
	using System.Collections.Generic;

	/// <summary>
	/// Represents a quantity of some item
	/// </summary>
	[ProtoContract]
	[Serializable]
	public class ItemQuantityCacheable : ICacheEntity
	{
		/// <summary>
		/// Creates a new instance of the ItemQuantityCacheable class.
		/// </summary>
		public ItemQuantityCacheable() { }

		/// <summary>
		/// The type of item this quanity is for
		/// </summary>
		[ProtoMember(1)]
		public BuildableItemEnum ItemCode { get; set; }

		/// <summary>
		/// The quantity of the item
		/// </summary>
		[ProtoMember(2)]
		public int Quantity { get; set; }

	}
}