///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Business.TableStorage
{
	using Common.BusinessObjects;
	using Microsoft.WindowsAzure.Storage.Table;
	using System;

	/// <summary>
	/// Represents a quantity of some item
	/// </summary>
	public class ItemQuantityTableStorage : TableEntity, ITableStorageEntity
	{
		/// <summary>
		/// Creates a new instance of the ItemQuantityTableStorage class.
		/// </summary>
		public ItemQuantityTableStorage() { }

		/// <summary>
		/// The type of item this quanity is for
		/// </summary>
		public int ItemCode { get; set; }

		/// <summary>
		/// The quantity of the item
		/// </summary>
		public int Quantity { get; set; }
	}
}