///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Business.Cache
{
	using Common.BusinessObjects;
	using ProtoBuf;
	using System;
	using System.Collections.Generic;

	/// <summary>
	/// Represents ongoing work that will produce some finished item(s) after some length of time
	/// </summary>
	[ProtoContract]
	[Serializable]
	public class WorkItemCacheable : ICacheEntity
	{
		/// <summary>
		/// Creates a new instance of the WorkItemCacheable class.
		/// </summary>
		public WorkItemCacheable() { }

		/// <summary>
		/// The item code representinf the item being worked on
		/// </summary>
		[ProtoMember(1)]
		public BuildableItemEnum ItemCode { get; set; }

		/// <summary>
		/// The UTC time when the work will be complete
		/// </summary>
		[ProtoMember(2)]
		public DateTime FinishTime { get; set; }
	}
}