///
/// Code audo generated by a tool other than you.
///
namespace KS.PizzaEmpire.Common.BusinessObjects
{
	using System;
	using System.Collections.Generic;

	/// <summary>
	/// Represents ongoing work that will produce some finished item(s) after some length of time
	/// </summary>
	public class WorkItem : IBusinessObjectEntity
	{
		/// <summary>
		/// Creates a new instance of the WorkItem class.
		/// </summary>
		public WorkItem() { }

		/// <summary>
		/// The item code representinf the item being worked on
		/// </summary>
		public BuildableItemEnum ItemCode { get; set; }

		/// <summary>
		/// The UTC time when the work will be complete
		/// </summary>
		public DateTime FinishTime { get; set; }
	}
}