namespace KS.PizzaEmpire.Unity
{
    public enum ResourceEnum
    {
        TEXTURE_ICON_TOMATO_LARGE = 0,
        TEXTURE_ICON_MORE_TEXT,
        TEXTURE_ICON_CHECKMARK,
        TEXTURE_TUTORIAL_LOUIE_0,
        TEXTURE_TUTORIAL_LOUIE_1,
        TEXTURE_TUTORIAL_LOUIE_2,
        TEXTURE_TUTORIAL_LOUIE_3,
        TEXTURE_TUTORIAL_LOUIE_4,
        TEXTURE_TUTORIAL_LOUIE_5,
        TEXTURE_TUTORIAL_LOUIE_6,
		TEXTURE_WHITE_FLOUR,
		TEXTURE_ICON_PHONE,
		TEXTURE_SHOPPING_CART,
        AUDIOCLIP_UNCLELOUIE,
        GUISTYLE_BASIC_STYLE,
        FONT_ARVO
    }
}