namespace KS.PizzaEmpire.Unity
{
    public enum ResourceEnum
    {       
		NONE = 0,
        TEXTURE_TUTORIAL_LOUIE_0,
        TEXTURE_TUTORIAL_LOUIE_1,
        TEXTURE_TUTORIAL_LOUIE_2,
        TEXTURE_TUTORIAL_LOUIE_3,
        TEXTURE_TUTORIAL_LOUIE_4,
        TEXTURE_TUTORIAL_LOUIE_5,
        TEXTURE_TUTORIAL_LOUIE_6,
		TEXTURE_ICON_COINS,
		TEXTURE_ICON_COUPONS,
		TEXTURE_ICON_TOMATO,
		TEXTURE_WHITE_FLOUR,
		TEXTURE_ICON_MORE_TEXT,
		TEXTURE_ICON_CHECKMARK,	
		TEXTURE_ICON_PHONE,
		TEXTURE_ICON_SHOPPING_CART,
		TEXTURE_ICON_DRYGOODSTAB,
		TEXTURE_ICON_VEGETABLESTAB,
		TEXTURE_BAR_OUTER,
		TEXTURE_BAR_INNER,
		TEXTURE_WIN_TUTORIAL_DIALOGUE,
		TEXTURE_WIN_ORDER_INGREDIENT,
		TEXTURE_UI_DISHCLOTH,
        AUDIOCLIP_UNCLELOUIE,
        GUISTYLE_BASIC_STYLE,
        GUISTYLE_NO_BACKGROUND,
		GUISTYLE_DEBUG,
        FONT_ARVO,
		PREFAB_DIRTY_TABLE,
		PREFAB_TABLE_CLOTH,
		PREFAB_DIRTY_DISHES,
		PREFAB_DISH_CLOTH
    }
}