namespace KS.PizzaEmpire.Common.BusinessObjects
{
    /// <summary>
    /// Represnts a list of all of the buildable items in the game
    /// </summary>
    public enum BuildableItemEnum
    {
        None = 0,
        White_Flour,
        Basil,        
        Olive_Oil,
        Salt,
        Pepper,
        Yeast,
        Tomatoes,
        Pineapple,
        Pepperoni,
        Ham,
        Cola_Syrup,
        Citrus_Syrup,
        Mozzarella_Cheese,
        Pizza_Box_S,
        Pizza_Box_M,
        Pizza_Box_L,
        White_Pizza_Dough,
        Basic_Pizza_Sauce,
        Sliced_Pepperoni,
        Sliced_Ham,
        Sliced_Pineapple,
        Grated_Mozzarella_Cheese,
        Cola_Soda,
        Citrus_Soda,
        Cheese_Pizza_S,
        Cheese_Pizza_M,
        Cheese_Pizza_L,
        Pepperoni_Pizza_S,
        Pepperoni_Pizza_M,
        Pepperoni_Pizza_L,
        Hawaiin_Pizza_S,
        Hawaiin_Pizza_M,
        Hawaiin_Pizza_L,
        Phone_L1,
        Dry_Goods_Delivery_Truck_L1,
        Vegetable_Farm_Delivery_Truck_L1,
        Meat_Farm_Delivery_Truck_L1,
        Dairy_Farm_Delivery_Truck_L1,
        Syrup_Delivery_Truck_L1,
        Pizza_Box_Delivery_Truck_L1,
        Motorcycle_L1,
        Cash_Register_L1,
        Pizza_Oven_L1,
        Cooking_Range_L1,
        Vegetable_Slicer_L1,
        Cheese_Grater_L1,
        Meat_Slicer_L1,
        Dough_Mixer_L1,
        Pizza_Assmebly_L1,
        Fridge_L1,
        Computer_L1,
        Customer_Seating_L1,
        Soda_Machine_L1,
        Restaurant_Storage,
        Dirty_Dishes
    }
}
