namespace KS.PizzaEmpire.Common.BusinessObjects
{
    /// <summary>
    /// Represnts a list of all of the buildable items in the game
    /// </summary>
    public enum BuildableItemEnum
    {
        None = 0,
        White_Flour,
        Basil,        
        Olive_Oil,
        Salt,
        Pepper,
        Yeast,
        Tomatoes,
        Pineapple,
        Pepperoni,
        Ham,
        Cola_Syrup,
        Citrus_Syrup,
        Mozzarella_Cheese,
        Pizza_Box,
        White_Pizza_Dough,
        Basic_Pizza_Sauce,
        Sliced_Pepperoni,
        Sliced_Ham,
        Sliced_Pineapple,
        Grated_Mozzarella_Cheese,
        Cola_Soda,
        Citrus_Soda,
        Cheese_Pizza,
        Pepperoni_Pizza,
        Hawaiin_Pizza,
        Phone,
        Dry_Goods_Delivery_Truck,
        Vegetable_Farm_Delivery_Truck,
        Meat_Farm_Delivery_Truck,
        Dairy_Farm_Delivery_Truck,
        Syrup_Delivery_Truck,
        Pizza_Box_Delivery_Truck,
        Motorcycle,
        Cash_Register,
        Pizza_Oven,
        Cooking_Range,
        Vegetable_Slicer,
        Cheese_Grater,
        Meat_Slicer,
        Dough_Mixer,
        Pizza_Assmebly,
        Fridge,
        Computer,
        Customer_Seating,
        Soda_Machine,
        Restaurant_Storage,
        Dirty_Dishes,
        Dirty_Table,
        Dirty_Floor
    }
}
